name: stardomain_strike
description: "Stardomain Strike - Reign over your star domain as the absolute ruler."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.20.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/img/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/img/app_icon_fg.png"
  adaptive_icon_background: "#0a1330"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/sound/
